etcd:
  schema: openIM
  address: [ 127.0.0.1:2379 ]
  username: aaa
  password:


zookeeper:
  schema: openIM
  address: [ 127.0.0.1:2181 ]
  username:
  password:

nacos:
  schema: openIM
  address: [ 127.0.0.1:8848 ]
  namespace: "8c2de99a-29d4-4a61-83aa-797e0327adea"
  username:
  password: