// 使用protobuf版本3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: hello2.proto

// proto文件中的包名

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	proto "grpc-demo/demo-1/hello-client/proto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestName string `protobuf:"bytes,1,opt,name=requestName,proto3" json:"requestName,omitempty"`
}

func (x *HelloRequest2) Reset() {
	*x = HelloRequest2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest2) ProtoMessage() {}

func (x *HelloRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_hello2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest2.ProtoReflect.Descriptor instead.
func (*HelloRequest2) Descriptor() ([]byte, []int) {
	return file_hello2_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest2) GetRequestName() string {
	if x != nil {
		return x.RequestName
	}
	return ""
}

type HelloResponse2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseMsg string `protobuf:"bytes,1,opt,name=responseMsg,proto3" json:"responseMsg,omitempty"`
}

func (x *HelloResponse2) Reset() {
	*x = HelloResponse2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponse2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse2) ProtoMessage() {}

func (x *HelloResponse2) ProtoReflect() protoreflect.Message {
	mi := &file_hello2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse2.ProtoReflect.Descriptor instead.
func (*HelloResponse2) Descriptor() ([]byte, []int) {
	return file_hello2_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse2) GetResponseMsg() string {
	if x != nil {
		return x.ResponseMsg
	}
	return ""
}

var File_hello2_proto protoreflect.FileDescriptor

var file_hello2_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x28, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x64, 0x65, 0x6d, 0x6f,
	0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x31, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32,
	0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x32, 0x0a, 0x0e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x32, 0x89, 0x01, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x39, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x14, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x32, 0x1a, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x22, 0x00, 0x12, 0x42,
	0x0a, 0x09, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x32, 0x12, 0x18, 0x2e, 0x64, 0x65,
	0x6d, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hello2_proto_rawDescOnce sync.Once
	file_hello2_proto_rawDescData = file_hello2_proto_rawDesc
)

func file_hello2_proto_rawDescGZIP() []byte {
	file_hello2_proto_rawDescOnce.Do(func() {
		file_hello2_proto_rawDescData = protoimpl.X.CompressGZIP(file_hello2_proto_rawDescData)
	})
	return file_hello2_proto_rawDescData
}

var file_hello2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hello2_proto_goTypes = []interface{}{
	(*HelloRequest2)(nil),       // 0: users.HelloRequest2
	(*HelloResponse2)(nil),      // 1: users.HelloResponse2
	(*proto.HelloRequest)(nil),  // 2: demoClient.HelloRequest
	(*proto.HelloResponse)(nil), // 3: demoClient.HelloResponse
}
var file_hello2_proto_depIdxs = []int32{
	0, // 0: users.SayHello.SayHello:input_type -> users.HelloRequest2
	2, // 1: users.SayHello.SayHello2:input_type -> demoClient.HelloRequest
	1, // 2: users.SayHello.SayHello:output_type -> users.HelloResponse2
	3, // 3: users.SayHello.SayHello2:output_type -> demoClient.HelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello2_proto_init() }
func file_hello2_proto_init() {
	if File_hello2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hello2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponse2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hello2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello2_proto_goTypes,
		DependencyIndexes: file_hello2_proto_depIdxs,
		MessageInfos:      file_hello2_proto_msgTypes,
	}.Build()
	File_hello2_proto = out.File
	file_hello2_proto_rawDesc = nil
	file_hello2_proto_goTypes = nil
	file_hello2_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SayHelloClient is the client API for SayHello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SayHelloClient interface {
	// rpc 方法名(请求参数) returns (返回参数)
	SayHello(ctx context.Context, in *HelloRequest2, opts ...grpc.CallOption) (*HelloResponse2, error)
	SayHello2(ctx context.Context, in *proto.HelloRequest, opts ...grpc.CallOption) (*proto.HelloResponse, error)
}

type sayHelloClient struct {
	cc grpc.ClientConnInterface
}

func NewSayHelloClient(cc grpc.ClientConnInterface) SayHelloClient {
	return &sayHelloClient{cc}
}

func (c *sayHelloClient) SayHello(ctx context.Context, in *HelloRequest2, opts ...grpc.CallOption) (*HelloResponse2, error) {
	out := new(HelloResponse2)
	err := c.cc.Invoke(ctx, "/users.SayHello/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sayHelloClient) SayHello2(ctx context.Context, in *proto.HelloRequest, opts ...grpc.CallOption) (*proto.HelloResponse, error) {
	out := new(proto.HelloResponse)
	err := c.cc.Invoke(ctx, "/users.SayHello/SayHello2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayHelloServer is the server API for SayHello service.
type SayHelloServer interface {
	// rpc 方法名(请求参数) returns (返回参数)
	SayHello(context.Context, *HelloRequest2) (*HelloResponse2, error)
	SayHello2(context.Context, *proto.HelloRequest) (*proto.HelloResponse, error)
}

// UnimplementedSayHelloServer can be embedded to have forward compatible implementations.
type UnimplementedSayHelloServer struct {
}

func (*UnimplementedSayHelloServer) SayHello(context.Context, *HelloRequest2) (*HelloResponse2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedSayHelloServer) SayHello2(context.Context, *proto.HelloRequest) (*proto.HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello2 not implemented")
}

func RegisterSayHelloServer(s *grpc.Server, srv SayHelloServer) {
	s.RegisterService(&_SayHello_serviceDesc, srv)
}

func _SayHello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayHelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.SayHello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayHelloServer).SayHello(ctx, req.(*HelloRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

func _SayHello_SayHello2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayHelloServer).SayHello2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.SayHello/SayHello2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayHelloServer).SayHello2(ctx, req.(*proto.HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SayHello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.SayHello",
	HandlerType: (*SayHelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SayHello_SayHello_Handler,
		},
		{
			MethodName: "SayHello2",
			Handler:    _SayHello_SayHello2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello2.proto",
}
